#!/usr/bin/env python3
"""Inventory of the files of a PS2 ISO (ISO9660).

For each file: path, LBA (2048-byte sector), size, first bytes.
No type is guessed: only universal signatures are named, the rest is shown raw to be studied in ImHex.

Usage: python scripts/inventory.py iso/dds1_us.iso
Output: docs/inventory.md and docs/inventory.csv
"""
import csv
import sys
from pathlib import Path

import pycdlib

SECTOR = 2048
HEAD = 16

# Publicly documented signatures, nothing game-specific.
SIGNATURES = {
    b"\x7fELF": "ELF (MIPS executable/module)",
    b"\x00\x00\x01\xba": "MPEG-PS (pack header)",
}


def ascii_preview(data: bytes) -> str:
    return "".join(chr(b) if 32 <= b < 127 else "." for b in data)


def classify(head: bytes, all_zero: bool | None) -> str:
    if all_zero:
        return "padding (100 % zeros)"
    for magic, name in SIGNATURES.items():
        if head.startswith(magic):
            return name
    return "unknown"


def is_all_zero(iso, path, size) -> bool:
    with iso.open_file_from_iso(iso_path=path) as f:
        while chunk := f.read(1 << 20):
            if chunk.count(0) != len(chunk):
                return False
    return True


def main(iso_file: str) -> None:
    iso = pycdlib.PyCdlib()
    iso.open(iso_file)
    rows = []
    for dirpath, _dirs, files in iso.walk(iso_path="/"):
        for name in files:
            path = f"{dirpath.rstrip('/')}/{name}"
            rec = iso.get_record(iso_path=path)
            size = rec.get_data_length()
            with iso.open_file_from_iso(iso_path=path) as f:
                head = f.read(HEAD)
            # "All zeros" test only for the big .DAT files suspected to be padding
            zero = is_all_zero(iso, path, size) if name.upper().startswith("ZZZ") else None
            rows.append({
                "path": path.split(";")[0],
                "lba": rec.extent_location(),
                "size": size,
                "sectors": -(-size // SECTOR),
                "head_hex": head.hex(" "),
                "head_ascii": ascii_preview(head),
                "type": classify(head, zero),
            })
    iso.close()
    rows.sort(key=lambda r: r["lba"])

    out = Path("docs")
    out.mkdir(exist_ok=True)
    with open(out / "inventory.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=rows[0].keys())
        w.writeheader()
        w.writerows(rows)

    with open(out / "inventory.md", "w") as f:
        f.write("# ISO inventory — generated by scripts/inventory.py\n\n")
        f.write("Sorted by LBA (physical order on the disc).\n\n")
        f.write("| LBA | Path | Size (bytes) | Size | First 16 bytes | ASCII | Type |\n")
        f.write("|---:|---|---:|---:|---|---|---|\n")
        for r in rows:
            f.write(f"| {r['lba']} | `{r['path']}` | {r['size']} | {human(r['size'])} | "
                    f"`{r['head_hex']}` | `{r['head_ascii']}` | {r['type']} |\n")
    print(f"{len(rows)} files -> docs/inventory.md, docs/inventory.csv")


def human(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "iso/dds1_us.iso")
